# Generated by Django 3.1.3 on 2020-11-21 10:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201121_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('expected_amount', models.DecimalField(decimal_places=6, max_digits=9)),
                ('production_price', models.DecimalField(decimal_places=6, max_digits=9)),
                ('expected_price', models.DecimalField(decimal_places=6, max_digits=9)),
                ('expected_ready_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_quantity', models.DecimalField(decimal_places=6, max_digits=9)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='api.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hedged_price', models.DecimalField(decimal_places=6, max_digits=9)),
                ('due_date', models.DateField()),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='api.batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='capability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.productioncapability'),
        ),
    ]
