# Generated by Django 3.1.3 on 2020-11-21 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201121_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioncapability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.product'),
        ),
    ]
